/*
 * This file was automatically generated by EvoSuite
 * Tue Aug 25 12:08:16 GMT 2026
 */

package org.apache.openjpa.lib.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.OutputStream;
import java.util.function.UnaryOperator;
import org.apache.openjpa.lib.util.LRUMap;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class LRUMap_ESTest extends LRUMap_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LRUMap lRUMap0 = new LRUMap();
      assertFalse(lRUMap0.isFull());
      
      lRUMap0.setMaxSize(0);
      assertEquals(0, lRUMap0.getMaxSize());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LRUMap lRUMap0 = new LRUMap(21);
      lRUMap0.setMaxSize(21);
      int int0 = lRUMap0.maxSize();
      assertEquals(21, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LRUMap lRUMap0 = new LRUMap();
      // Undeclared exception!
      try { 
        lRUMap0.setMaxSize((-1485));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // -1485
         //
         verifyException("org.apache.openjpa.lib.util.LRUMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LRUMap lRUMap0 = new LRUMap();
      OutputStream outputStream0 = OutputStream.nullOutputStream();
      ObjectOutputStream objectOutputStream0 = new ObjectOutputStream(outputStream0);
      lRUMap0.doWriteObject(objectOutputStream0);
      assertEquals(100, lRUMap0.getMaxSize());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      LRUMap lRUMap0 = new LRUMap();
      // Undeclared exception!
      try { 
        lRUMap0.doReadObject((ObjectInputStream) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"java.io.ObjectInputStream.readInt()\" because \"input\" is null
         //
         verifyException("org.apache.openjpa.lib.util.LRUMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      LRUMap lRUMap0 = new LRUMap();
      UnaryOperator<Integer> unaryOperator0 = UnaryOperator.identity();
      lRUMap0.computeIfAbsent(unaryOperator0, unaryOperator0);
      LRUMap lRUMap1 = null;
      try {
        lRUMap1 = new LRUMap(lRUMap0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Entry.next=null, data[removeIndex]=null previous=null key=java.util.function.UnaryOperator$$Lambda$294/0x000000b8011de748@3d2e02b0 value=java.util.function.UnaryOperator$$Lambda$294/0x000000b8011de748@3d2e02b0 size=0 maxSize=1 This should not occur if your keys are immutable, and you have used synchronization properly.
         //
         verifyException("org.apache.openjpa.lib.util.collections.LRUMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      LRUMap lRUMap0 = new LRUMap();
      int int0 = lRUMap0.getMaxSize();
      assertEquals(100, int0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      LRUMap lRUMap0 = new LRUMap(1, 1);
      lRUMap0.setMaxSize(1);
      Integer integer0 = new Integer(2323);
      UnaryOperator<Integer> unaryOperator0 = UnaryOperator.identity();
      lRUMap0.computeIfAbsent(integer0, unaryOperator0);
      assertTrue(lRUMap0.isFull());
  }
}
