/*
 * This file was automatically generated by EvoSuite
 * Wed Aug 05 13:52:40 GMT 2026
 */

package org.apache.openjpa.lib.evosuite;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.FilterOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.HashMap;
import java.util.function.UnaryOperator;
import org.apache.openjpa.lib.util.LRUMap;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFileOutputStream;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class LRUMap_ESTest extends LRUMap_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LRUMap lRUMap0 = new LRUMap(1);
      lRUMap0.setMaxSize(1);
      boolean boolean0 = lRUMap0.isFull();
      assertEquals(1, lRUMap0.getMaxSize());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LRUMap lRUMap0 = new LRUMap();
      lRUMap0.setMaxSize(0);
      int int0 = lRUMap0.maxSize();
      assertTrue(lRUMap0.isFull());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LRUMap lRUMap0 = new LRUMap();
      // Undeclared exception!
      try { 
        lRUMap0.setMaxSize((-1517));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // -1517
         //
         verifyException("org.apache.openjpa.lib.util.LRUMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      HashMap<Object, Object> hashMap0 = new HashMap<Object, Object>();
      hashMap0.put(hashMap0, hashMap0);
      LRUMap lRUMap0 = null;
      try {
        lRUMap0 = new LRUMap(hashMap0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Entry.next=null, data[removeIndex]=null previous=null key={(this Map)=(this Map)} value={(this Map)=(this Map)} size=0 maxSize=1 This should not occur if your keys are immutable, and you have used synchronization properly.
         //
         verifyException("org.apache.openjpa.lib.util.collections.LRUMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      LRUMap lRUMap0 = new LRUMap(1);
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("%7`+1XJ~TpN>17");
      FilterOutputStream filterOutputStream0 = new FilterOutputStream(mockFileOutputStream0);
      ObjectOutputStream objectOutputStream0 = new ObjectOutputStream(filterOutputStream0);
      lRUMap0.doWriteObject(objectOutputStream0);
      assertEquals(1, lRUMap0.getMaxSize());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      LRUMap lRUMap0 = new LRUMap();
      // Undeclared exception!
      try { 
        lRUMap0.doReadObject((ObjectInputStream) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"java.io.ObjectInputStream.readInt()\" because \"in\" is null
         //
         verifyException("org.apache.openjpa.lib.util.LRUMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      LRUMap lRUMap0 = new LRUMap();
      UnaryOperator<Object> unaryOperator0 = UnaryOperator.identity();
      lRUMap0.computeIfAbsent("{}", unaryOperator0);
      assertEquals(100, lRUMap0.getMaxSize());
      
      lRUMap0.setMaxSize(0);
      assertEquals(0, lRUMap0.getMaxSize());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      LRUMap lRUMap0 = new LRUMap();
      int int0 = lRUMap0.getMaxSize();
      assertEquals(100, int0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      LRUMap lRUMap0 = new LRUMap(1, 958.0F);
      assertFalse(lRUMap0.isFull());
  }
}
