/*
 * This file was automatically generated by EvoSuite
 * Tue Aug 25 12:37:36 GMT 2026
 */

package org.apache.openjpa.lib.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.HashMap;
import java.util.function.BiFunction;
import org.apache.openjpa.lib.util.LRUMap;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.io.MockFileInputStream;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class LRUMap_ESTest extends LRUMap_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LRUMap lRUMap0 = new LRUMap(2320, 2320);
      assertEquals(2320, lRUMap0.maxSize());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LRUMap lRUMap0 = new LRUMap();
      assertEquals(100, lRUMap0.getMaxSize());
      
      lRUMap0.setMaxSize(1);
      boolean boolean0 = lRUMap0.isFull();
      assertEquals(1, lRUMap0.maxSize());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LRUMap lRUMap0 = new LRUMap();
      // Undeclared exception!
      try { 
        lRUMap0.setMaxSize((-7));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // -7
         //
         verifyException("org.apache.openjpa.lib.util.LRUMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LRUMap lRUMap0 = new LRUMap();
      // Undeclared exception!
      try { 
        lRUMap0.doWriteObject((ObjectOutputStream) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"java.io.ObjectOutputStream.writeInt(int)\" because \"out\" is null
         //
         verifyException("org.apache.openjpa.lib.util.LRUMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      LRUMap lRUMap0 = new LRUMap();
      Object object0 = new Object();
      BiFunction<MockFileInputStream, Integer, MockFileInputStream> biFunction0 = (BiFunction<MockFileInputStream, Integer, MockFileInputStream>) mock(BiFunction.class, new ViolatedAssumptionAnswer());
      lRUMap0.merge((Object) null, object0, biFunction0);
      assertFalse(lRUMap0.isFull());
      
      lRUMap0.setMaxSize(0);
      assertEquals(0, lRUMap0.maxSize());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      LRUMap lRUMap0 = new LRUMap(19);
      assertEquals(19, lRUMap0.getMaxSize());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      LRUMap lRUMap0 = new LRUMap();
      // Undeclared exception!
      try { 
        lRUMap0.doReadObject((ObjectInputStream) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"java.io.ObjectInputStream.readInt()\" because \"in\" is null
         //
         verifyException("org.apache.openjpa.lib.util.LRUMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      LRUMap lRUMap0 = new LRUMap();
      assertFalse(lRUMap0.isFull());
      
      lRUMap0.setMaxSize(0);
      int int0 = lRUMap0.getMaxSize();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      HashMap<Integer, Object> hashMap0 = new HashMap<Integer, Object>();
      hashMap0.put((Integer) null, (Object) null);
      LRUMap lRUMap0 = null;
      try {
        lRUMap0 = new LRUMap(hashMap0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Entry.next=null, data[removeIndex]=null previous=null key=null value=null size=0 maxSize=1 This should not occur if your keys are immutable, and you have used synchronization properly.
         //
         verifyException("org.apache.openjpa.lib.util.collections.LRUMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      LRUMap lRUMap0 = new LRUMap();
      int int0 = lRUMap0.getMaxSize();
      assertEquals(100, int0);
  }
}
