/*
 * This file was automatically generated by EvoSuite
 * Tue Aug 25 12:41:43 GMT 2026
 */

package org.apache.openjpa.lib.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.HashMap;
import java.util.function.Function;
import java.util.function.UnaryOperator;
import org.apache.openjpa.lib.util.LRUMap;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class LRUMap_ESTest extends LRUMap_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LRUMap lRUMap0 = new LRUMap();
      UnaryOperator<Object> unaryOperator0 = UnaryOperator.identity();
      Function<Object, Object> function0 = Function.identity();
      lRUMap0.put(unaryOperator0, function0);
      assertEquals(100, lRUMap0.maxSize());
      
      lRUMap0.setMaxSize(0);
      assertEquals(0, lRUMap0.maxSize());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LRUMap lRUMap0 = new LRUMap();
      lRUMap0.setMaxSize(8);
      Object object0 = new Object();
      UnaryOperator<Object> unaryOperator0 = UnaryOperator.identity();
      lRUMap0.computeIfAbsent(object0, unaryOperator0);
      assertEquals(8, lRUMap0.getMaxSize());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LRUMap lRUMap0 = new LRUMap();
      lRUMap0.setMaxSize(8);
      int int0 = lRUMap0.maxSize();
      assertEquals(8, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LRUMap lRUMap0 = new LRUMap();
      // Undeclared exception!
      try { 
        lRUMap0.setMaxSize((-672));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // -672
         //
         verifyException("org.apache.openjpa.lib.util.LRUMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      LRUMap lRUMap0 = new LRUMap();
      // Undeclared exception!
      try { 
        lRUMap0.doWriteObject((ObjectOutputStream) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"java.io.ObjectOutputStream.writeInt(int)\" because \"out\" is null
         //
         verifyException("org.apache.openjpa.lib.util.LRUMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      LRUMap lRUMap0 = new LRUMap(3100);
      assertEquals(3100, lRUMap0.getMaxSize());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      LRUMap lRUMap0 = new LRUMap();
      // Undeclared exception!
      try { 
        lRUMap0.doReadObject((ObjectInputStream) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"java.io.ObjectInputStream.readInt()\" because \"in\" is null
         //
         verifyException("org.apache.openjpa.lib.util.LRUMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      HashMap<Object, Object> hashMap0 = new HashMap<Object, Object>();
      Integer integer0 = new Integer((-63));
      hashMap0.put(integer0, integer0);
      LRUMap lRUMap0 = null;
      try {
        lRUMap0 = new LRUMap(hashMap0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Entry.next=null, data[removeIndex]=null previous=null key=-63 value=-63 size=0 maxSize=1 This should not occur if your keys are immutable, and you have used synchronization properly.
         //
         verifyException("org.apache.openjpa.lib.util.collections.LRUMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      LRUMap lRUMap0 = new LRUMap();
      int int0 = lRUMap0.getMaxSize();
      assertEquals(100, int0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      LRUMap lRUMap0 = new LRUMap(1, 0.75F);
      assertFalse(lRUMap0.isFull());
  }
}
