name: Milestone 4 - Testing & Refactoring CI
on:
  push:
    branches: [ ispw-project ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: temurin
          cache: maven

      - name: Build OpenJPA
        run: |
          mvn -B clean install \
          -Dmaven.test.skip=true \
          -Dinvoker.skip=true \
          -Dcheckstyle.skip=true \
          -Drat.skip=true

      - name: Run LRUMap tests
        run: |
          mvn -B -pl :openjpa-lib test \
          -Dtest=*Test,!*_ESTest \
          -Dcheckstyle.skip=true \
          -Drat.skip=true

      - name: Run Filters tests
        run: |
          mvn -B -pl :openjpa-kernel test \
            -Dtest=*Test,!*_ESTest \
            -Dcheckstyle.skip=true \
            -Drat.skip=true

      - name: Generate JaCoCo reports
        if: always()
        run: |
          mvn jacoco:report -pl :openjpa-lib,:openjpa-kernel

      - name: Upload JaCoCo reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-reports
          path: |
            openjpa-lib/target/site/jacoco/
            openjpa-kernel/target/site/jacoco/

      - name: Run PIT
        if: always()
        run: |
          mvn -B -pl :openjpa-lib,:openjpa-kernel pitest:mutationCoverage
          

      - name: Upload PIT reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pit-reports
          path: |
            openjpa-lib/target/pit-reports/
            openjpa-kernel/target/pit-reports/




